### PR TITLE
Set min python to 3.8

### LINKED ISSUE #75: 2023.3 breaks Python 3.7
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The latest release of `fsspec` has dropped support for 3.7. Though this has not been done on `conda-forge`, which means that the package currently fails on import, with this error:

``` python-traceback
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsspec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shh/miniconda3/envs/tmptmptmp/lib/python3.7/site-packages/fsspec/__init__.py", line 1, in <module>
    from importlib.metadata import entry_points
ModuleNotFoundError: No module named 'importlib.metadata'
```

`mamba create -n tmptmptmp python=3.7 fsspec`  and then import `fsspec`

### Installed packages

```shell
# packages in environment at /home/shh/miniconda3/envs/tmptmptmp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
fsspec                    2023.3.0           pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                67.5.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : tmptmptmp
    active env location : /home/shh/miniconda3/envs/tmptmptmp
            shell level : 4
       user config file : /home/shh/.condarc
 populated config files : /home/shh/miniconda3/.condarc
                          /home/shh/.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=6.1.11=0
                          __unix=0=0
       base environment : /home/shh/miniconda3  (writable)
      conda av data dir : /home/shh/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/shh/miniconda3/pkgs
                          /home/shh/.conda/pkgs
       envs directories : /home/shh/miniconda3/envs
                          /home/shh/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.9 Linux/6.1.11-76060111-generic pop/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes #75.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martindurant** [comment]
I keep getting this wrong :|

Unfortunately this won't be enough, we need to  patch the metadata on the existing build

**Comment by martindurant** [comment]
@conda-forge-admin , what do I need to do to update the python required version on the build that already went out? Or simply removing that build would be fine.

**Comment by Hoxbro** [comment]
I think you meant to call @conda-forge/core

**Comment by ianthomas23** [comment]
There is some info at https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages about how to do this. As we only need to patch the metadata, I think we only need to create a PR on `conda-forge-repodata-patches-feedstock`. There is a recent example of changing the minimum python version in this PR: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/407/files

**Pull request merged**
